name: mikekiernan
favicon: null
layout_spectrum: 0.9766615584958345
typography_spectrum: 0.6228394245263189
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3043241910636425
  lightness: 0.036578333703801036
  saturation: 0.4256294392980635
  rhythmicContrast: 0.5227368860505521
purpose: []
